version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-q', '-O-', 'http://localhost:3000/']
      interval: 30s
      timeout: 5s
      retries: 3
